# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.form.registration:
        class: BoxBundle\Form\UserType
        tags:
            - { name: form.type, alias: fos_user_registration_register }
#            - { phone: form.type, alias: app_user_profile }
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
